name: lint

on:
  workflow_call:

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest

    permissions:
      checks: write
      contents: write

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install npm
        run: npm -g install npm

      - name: Set package.json config.cli
        run: sed -i 's/.*"cli":.*/"cli":"npm"/' package.json

      - name: Install package dependencies
        run: npm install

      - name: Run linter
        run: npx lint-staged --diff="origin/${GITHUB_BASE_REF}...origin/${GITHUB_HEAD_REF}"
